### PR TITLE
Buff daggers and replace wildcard imports

### PR DESCRIPTION
**Pull request by Quetz4l**
(It could change the balance)
---
BM dagger (for self usege): 
* 200 without debuff and 20 with the debuff (Soul Fray)

BMA - Glass Sacrificial Dagger (for self usege): 
* 500 without debuff and 50 with the debuff (Soul Fray)
* \+ x2 blood for both with 10% (added)

----

BM dagger (for mobs):
* calculate a value

BMA - Glass Dagger of Sacrifice (for mobs):
was: if some mobs value +100 else value =500 (villager +500)
now: 
* calculate a value and  if mob is "villager" value +500 (2500) else  value + 100 (added)
* \+ x5 blood for villager with 30% (added)
* \+ x5 blood for all except for the vanilla villagers with 20% (added)
----
added support for moon villagers and guardians

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15044
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15043

* replaced all wildcard imports in the mod

### CODE REVIEW

**Comment by Dream-Master** [comment]
Is Soul Fray not a debuff to prevent players from sacrifice to death and can cheat in as much blood they want. 
Can you list the values before your changes?

I am not sure if this is balanced.

**Comment by Quetz4l** [comment]
> Is Soul Fray not a debuff to prevent players from sacrifice to death and can cheat in as much blood they want. Can you list the values before your changes?
> 
> I am not sure if this is balanced.

I haven't changed mechanics since (Soul Fray).
In the PR description I described what was there, what I added and what in the blood magic.

**Comment by Dream-Master** [comment]
ok but i dont see what are old values and what are the new ones. Like BM dagger (for self usege): old/new values etc

**Comment by Quetz4l** [comment]
I didn't change the blood magic. I put it in the description to compare because there are 2 daggers each. One in blood magic and one in blood arsenal. In blood arsenal they are harder to make and should be better, I only changed them.

**Comment by Dream-Master** [comment]
ok. so before they make no difference which dagger you have ?

**Comment by Quetz4l** [comment]
Previously in blood arsenal daggers with mobs were worse, since the author did not take into account the inhabitants and set the exact value of 500 blood except for 4 types of mobs. These 4 types of mobs gave more by 100 each, while villages gave thousands less (guard gave 3500 less blood and etc.).

**Comment by Quetz4l** [comment]
But the dagger for self gave more and worked better. BM 200, BMA 500

**Comment by Dream-Master** [comment]
ok but isnt there a list how much each mob gives? I rember i saw a list long time ago (config)

**Comment by Quetz4l** [comment]
these values are taken from Blood magic, then I add 100, 500 or multiply that value by 5

**Comment by Dream-Master** [comment]
ok. guess it need to be discussed when feature freeze is over.

**Comment by Alastors** [comment]
Why wait until after the freeze? It's not new content?

**Comment by Quetz4l** [comment]
> Why wait until after the freeze? It's not new content?

It's a rebalancing and there's always room for unforeseen bugs.

**Comment by vovaksenov** [comment]
Looks good imo. Hopefully this helps with the pre-ritual mob spam a bit. I like the values.

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
